name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag msu:latest
    - name: Docker Login
      run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Tag docker image
      run: docker tag msu:latest bigoli98/microservice-updater:latest
    - name: Push docker image
      run: docker push bigoli98/microservice-updater:latest
